### ISSUE TITLE
Cannot find module 'yes-kafka' after upgrade to 1.0.6

### ISSUE THREAD

**Issue by alexeevg** [mnorkin/yes-kafka#11]
```
$ npm i yes-kafka@latest

+ yes-kafka@1.0.6
removed 2 packages and updated 1 package in 1.977s
$ node
> require('yes-kafka')
Thrown:
{ Error: Cannot find module 'yes-kafka'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
>
```
